GET http://localhost:8080/
Accept: application/json

###

POST http://localhost:8080/expenses
Content-Type: application/json

{
  "amount": 76.56,
  "currency": "EUR",
  "instant": 1575132000
}

###

GET http://localhost:8080/expenses
Accept: application/json

###
