GET http://localhost:8080/
Accept: application/json

###

POST http://localhost:8080/expenses
Content-Type: application/json

{
  "amount": 76.56,
  "currency": "EUR",
  "instant": 1575132000
}
###

POST http://localhost:8080/expenses
Content-Type: application/json

{
  "amount": 87435,
  "currency": "JPY",
  "instant": 1575139999
}

###

GET http://localhost:8080/expenses
Accept: application/json

###

GET http://localhost:8080/expenses/e285977f-3ae9-4417-be4a-42e234ac0a41
Accept: application/json

###
